# Generated by Django 3.2 on 2021-04-13 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210413_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='banner',
            field=models.FileField(blank=True, upload_to='banners/'),
        ),
    ]
