# Generated by Django 3.2 on 2021-04-13 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210413_1522'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Postagem',
        ),
    ]
