# Generated by Django 3.2 on 2021-04-14 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210414_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='postfile',
            name='name',
            field=models.CharField(default='vool', max_length=50),
            preserve_default=False,
        ),
    ]
