# Generated by Django 3.2 on 2021-04-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_postfile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slang',
            field=models.CharField(default='blog-name', max_length=25),
            preserve_default=False,
        ),
    ]
