# Generated by Django 3.2 on 2021-04-16 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20210415_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='slang',
        ),
        migrations.AddField(
            model_name='post',
            name='last_edited_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
