# Generated by Django 3.2 on 2021-04-16 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20210416_0632'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.CharField(default='nothing', max_length=30),
            preserve_default=False,
        ),
    ]
